### ISSUE TITLE
Lighthouse audit says well done

### ISSUE THREAD

**Issue by freemvmt** [fac19/week10-hettiehannah#30]
Yep, nice result here!

![image](https://user-images.githubusercontent.com/29084012/81393474-57699000-9118-11ea-9807-01e0d86d0dee.png)

Obviously this indicates there's something to do on the accessibility front. The fix is easy - I think it involves only 5 key presses :)

**Comment by hannahgooding** [comment]
![Screenshot 2020-05-08 at 11 38 17](https://user-images.githubusercontent.com/47333850/81398081-6fdda880-9120-11ea-9810-eeb9f457d6e4.png)
woo!
